# COMS 3251 Spring 2022: Homework 2

**Instructions**: Solve all problems and type up your solutions in this notebook. Each solution should appear in a new text or code cell immediately following the given problem. Written problems should include work and steps in addition to the answers; $\LaTeX$ is highly recommended, but plaintext is also acceptable if it is understandable. If permitted to use code, coding solutions should be free of errors, and all outputs should be left in the notebook for submission.

**Submission**: Submit a PDF printout of this notebook to Gradescope (not the .ipynb file). One way to do so is to download and then open the file in Google Colab (accessible from your LionMail account). Inspect to make sure that all cells are expanded and outputs are present, and then "print as PDF". Then upload the file to Gradescope. Please be sure to tag your pages.

All submitted work must be your own. Cases of academic dishonesty will be addressed following the policies outlined on the course syllabus.

In [24]:
# RUN THIS FIRST
import numpy as np
import matplotlib.pyplot as plt

# Problem 1 (15 points)

Consider the following augmented matrix for the equation $A \mathbf x = \mathbf b$:

$$ \begin{bmatrix} A & | & \mathbf b \end{bmatrix} = 
\begin{bmatrix}
0 & \alpha & 0 & | & \beta \\ 0 & 0 & 2 & | & 4 \\ 1 & 0 & 3 & | & 0
\end{bmatrix} $$

1. For what values of $\alpha$ and $\beta$ does the system have a unique solution? Find the solution $(x_1, x_2, x_3)$ in terms of $\alpha$ and $\beta$.

2. For what values of $\alpha$ and $\beta$ does the system have no solution? What is the inconsistent "equation" that results from the augmented matrix?

3. For what values of $\alpha$ and $\beta$ does the system have many solutions? Write down the corresponding set of equations in this case. What are the free variables? 



YOUR SOLUTIONS HERE 

1. Since the second and third row of the matrix give a concrete solution to the system of equations for the $x_1$ and $x_3$ variables and in both rows the coefficient in front of $x_2$ is 0, then $x_2$'s value is determined only from row 1. From row 1 we can get the solution: $x_2 = \frac{\beta}{\alpha}$. However, that's, of course, given some restriction - namely - to be able to divide by $\alpha$ i.e. $\alpha \ne 0$. In order to cover this "special" case, we need to look into 2 possible scenarios:
$$\\ \begin{cases} \alpha x_2 = 0, & \alpha = 0 \\  x_2 = \frac{\beta}{\alpha}, & \alpha \ne 0\end{cases}$$ It's easy to recognize that the first case will either result in zero or infinite solutions, depending on the value of $\beta$. More precisely, we'll have the following case: 
$$\\ \begin{cases} \beta = 0,  \alpha = 0 => x_2 \ can\ be\ any\ number\ in\ \mathbb{R}\  (or\ \mathbb{C}) \\ \beta \ne 0, \alpha = 0 => there\ are\ no\ solutions\ for\ x_2\ in\ \mathbb{R}\ (or\ \mathbb{C}) \end{cases}$$ Thus, the system has a unique solution for the case when $\alpha \ne 0$ and the solution is $x_2 = \frac{\beta}{\alpha}$ => The full solution is: $$ \begin{bmatrix}x_1 \\ x_2 \\ x_3 \end{bmatrix} = \begin{bmatrix}-6 \\ \frac{\beta}{\alpha} \\ 2 \end{bmatrix} $$

2. As discussed in part 1, we'll have no solutions if $\beta \ne 0, \alpha = 0$. The inconsistent "equation" is the following: $\alpha x_2 = \beta$, which, when we plug in the values for $\alpha$ and $\beta$, transfroms into the following: $0 x_2 = \beta$ for $\beta \ne 0$, which obviosuly has no solutions.

3. As discussed in part 1, we'll have many (more precisely, infinite number of) solutions in the case when $\beta = 0, \alpha = 0$. That is because, $x_2$ can be any number and it will still satisfy the system of equations. The corresponding set of equations is as follows: 
$$\begin{cases} 0x_1 + \alpha x_2 + 0x_3= \beta \\  0 x_1 + 0 x_2 + 2 x_3 = 4 \\ 1 x_1 + 0x_2 + 3x_3 = 0\end{cases}$$ and when we plug $\alpha = 0  \ and\  \beta = 0$, we'll get:
$$\\ \begin{cases} 0x_1 + 0 x_2 + 0x_3= 0 \\  0 x_1 + 0 x_2 + 2 x_3 = 4 \\ 1 x_1 + 0x_2 + 3x_3 = 0\end{cases}$$
Now, given the above equations, we can easily create the RREF matrix: 
$$ \begin{bmatrix}
1 & 0 & 3 & | & 0 \\ 0 & 0 & 1 & | & 2 \\ 0 & 0 & 0 & | & 0 \end{bmatrix} $$ Given this, we can see that the first and third variables are leading/pivot variables => The second variable is a free variable! 



# Problem 2 (15 points)

Consider the following matrix:

$$A =  \begin{bmatrix} 2&3&1 \\ 4&7&5 \\ 0&-2&2 \end{bmatrix}$$

1. Suppose we have the matrix $I_3$ and we want to transform it into $A^{-1}$ by multiplying it by a sequence of elementary matrices. Find a suitable set of elementary matrices and compute their product $X$ (you may use Python).

2. Consider the product $X\mathbf b$, where $\mathbf b$ is some arbitrary 3-vector. What linear system is this product a solution of? Does this interpretation hold for any vector $\mathbf b$?

3. For which vector $\mathbf b$ would the product $X \mathbf b$ be the first column of $A^{-1}$? How about the second column of $A^{-1}$ The third column?

YOUR SOLUTIONS HERE 

1. Firstly we need to get the matrix in REF. We do this by using row operations.
Firstly, we see that the first element in the second row is a 4 and, thus, we should make it a zero. This can happen with the transformation: 
$R_2 \rightarrow R_2 - 2*R_1$. Now the second row will become: $$\begin{bmatrix} 4 & 7 & 5 \end{bmatrix} - 2 \begin{bmatrix} 2 & 3 & 1 \end{bmatrix} = \begin{bmatrix} 0 & 1 & 3 \end{bmatrix} $$ Now, the whole matrix looks like: $$A =  \begin{bmatrix} 2&3&1 \\ 0&1&3 \\ 0&-2&2 \end{bmatrix}$$ The only thing left is to make A[2][1] = 0. This can happen with the transformation: $R_3 \rightarrow R_3 + 2*R_2$. After this transformation $R_3$ will become: $$\begin{bmatrix} 0 & -2 & 2 \end{bmatrix} + 2 \begin{bmatrix} 0 & 1 & 3 \end{bmatrix} = \begin{bmatrix} 0 & 0 & 8 \end{bmatrix} $$ => Finally, the matrix will be in REF:
$$A =  \begin{bmatrix} 2&3&1 \\ 0&1&3 \\ 0&0&8 \end{bmatrix}$$ Now, finally, to get to RREF, we need to do the follwing 2 transformations to get A[0][0] = 1 and A[2][2] = 1. 
$$\\ \begin{cases} R_1 \rightarrow \frac{1}{2}R_1 \\ R_3 \rightarrow \frac{1}{8}R_3 \end{cases}$$
The elementary matricies for this are as follows: 

    1. $R_2 \rightarrow R_2 - 2*R_1$
        * a) $R_1 \rightarrow - 2*R_1$
        $$ X_1 = 
            \begin{bmatrix}
            -2 & 0 & 0 \\ 
            0 & 1 & 0 \\
            0 & 0 & 1 
            \end{bmatrix} $$
        * b) $R_2 \rightarrow R_2 + R_1$
        $$ X_2 = 
            \begin{bmatrix}
            1 & 0 & 0 \\ 
            1 & 1 & 0 \\
            0 & 0 & 1 
            \end{bmatrix} $$
        * c) $R_1 \rightarrow -\frac{1}{2}*R_1$
        $$ X_3 = 
            \begin{bmatrix}
            -\frac{1}{2} & 0 & 0 \\ 
            0 & 1 & 0 \\
            0 & 0 & 1 
            \end{bmatrix} $$
    2. $R_3 \rightarrow R_3 + 2*R_2$
        * a) $R_2 \rightarrow 2*R_2$
        $$ X_4 = 
            \begin{bmatrix}
            1 & 0 & 0 \\ 
            0 & 2 & 0 \\
            0 & 0 & 1 
            \end{bmatrix} $$
        * b) $R_3 \rightarrow R_3 + R_2$
        $$ X_5 = 
            \begin{bmatrix}
            1 & 0 & 0 \\ 
            0 & 1 & 0 \\
            0 & 1 & 1 
            \end{bmatrix} $$
        * c) $R_2 \rightarrow \frac{1}{2}*R_2$
        $$ X_6 = 
            \begin{bmatrix}
            1 & 0 & 0 \\ 
            0 & \frac{1}{2} & 0 \\
            0 & 0 & 1 
            \end{bmatrix} $$
    3. $R_1 \rightarrow \frac{1}{2}R_1$
         $$ X_7 = 
            \begin{bmatrix}
            \frac{1}{2} & 0 & 0 \\ 
            0 & 1 & 0 \\
            0 & 0 & 1 
            \end{bmatrix} $$
    4. $R_3 \rightarrow \frac{1}{8}R_3$
         $$ X_8 = 
            \begin{bmatrix}
            1 & 0 & 0 \\ 
            0 & 1 & 0 \\
            0 & 0 & \frac{1}{8} 
            \end{bmatrix} $$
    
    Now, using Python we can calculate $X$ = ${\displaystyle \prod_{i=8}^{1} X_{i}}$. The calculations are below and the final matrix is: 
    $$X =  \begin{bmatrix} \frac{1}{2}&0&0 \\ -2&1&0 \\ -\frac{1}{2}&\frac{1}{4}&\frac{1}{8} \end{bmatrix}$$

2. If we consider the vector $\mathbf x  = X\mathbf b$, then $A\mathbf x = A(X\mathbf b) = (AX)\mathbf b = I\mathbf b = \mathbf b$. => The linear system is $A \mathbf x = \mathbf b$. It also holds for all values of $\mathbf b$!

3. For the 3 questions the answers are respectively: 1) (1, 0, 0); 2) (0, 1, 0); 3) (0, 0, 1). This is because of the matrix multiplication properties. Multiplying those vectors with $X$ would give us the desired columns.



In [40]:
# ENTER ANY CODE HERE

# Problem 2.1

# Calculating the X matrix for 4c):

X_1 = np.array([[-2, 0, 0],
                [0,  1, 0],
                [0,  0, 1]])

X_2 = np.array([[1, 0, 0],
                [1, 1, 0],
                [0, 0, 1]])

X_3 = np.array([[-0.5, 0, 0],
                [0, 1,    0],
                [0, 0,    1]])

X_4 = np.array([[1, 0, 0],
                [0, 2, 0],
                [0, 0, 1]])

X_5 = np.array([[1, 0, 0],
                [0, 1, 0],
                [0, 1, 1]])

X_6 = np.array([[1, 0,   0],
                [0, 0.5, 0],
                [0, 0,   1]])

X_7 = np.array([[0.5, 0, 0],
                [0,   1, 0],
                [0,   0, 1]])

X_8 = np.array([[1, 0,     0],
                [0, 1,     0],
                [0, 0, 0.125]])

A = np.array([[2, 3, 1],
              [4, 7, 5],
              [0, -2, 2]])

result = X_8 @ (X_7 @ (X_6 @ (X_5 @ (X_4 @ (X_3 @ (X_2 @ X_1))))))
print(result)
print()

print(result @ A) # for check

[[ 0.5    0.     0.   ]
 [-2.     1.     0.   ]
 [-0.5    0.25   0.125]]

[[1.  1.5 0.5]
 [0.  1.  3. ]
 [0.  0.  1. ]]


# Problem 3 (15 points)

The set $\mathbb C$ of all complex numbers, with the usual operations of addition and real scalar multiplication, forms a vector space. Elements of $\mathbb C$ can be written in the form $x + iy$, where $i$ is the imaginary unit.

1. Show that closure is satisfied for $\mathbb C$ under addition and scalar multiplication. What is the zero "vector" in this vector space?

2. Come up with two different subspaces of $\mathbb C$ other than $\{\mathbf 0\}$ and $\mathbb C$ itself. Explain how they satisfy the definition of a subspace.

3. $\mathbb R$ is closed under multiplication; in other words, the product of two elements in $\mathbb R$ is also in $\mathbb R$. Can we say the same for $\mathbb C$? Why or why not?

ENTER WRITTEN RESPONSES HERE

1. We want to prove that for any  two arbitrary numbers in $\mathbb C$, their sum and product are also in $\mathbb C$. We can represent any number in $\mathbb C$ by a column vector where the first row contains the real part of the number and second row contains the imaginary. Thus, if we define two arbitrary complex numbers: 
$$ \begin{bmatrix}
x_1 \\ y_1 \end{bmatrix}\ and\ \begin{bmatrix}
x_2 \\ y_2 \end{bmatrix}$$ their respective sum and product will be: $$ \begin{bmatrix}
x_1 + x_2 \\ y_1 + y_2 \end{bmatrix}\ and\ \begin{bmatrix}
x_1x_2 \\ y_1y_2 \end{bmatrix}$$Now, since $\mathbb C$ is defined as $\mathbb R^2$ because we are essentially choosing values for $x$ and $y$, where $x, y \in \mathbb R$ to "construct" the complex number $x + iy$. Since we know that for any 2 numbers $x_1 \in \R$ and $x_2 \in \R$, their product and sum also lie in the set of real numbers: $x_1 x_2 \in \R, (x_1 + x_2) \in \R$. Since this is true and we are looking for a function that maps $f: (\R^2, \R^2) \rightarrow \R^2$. Since the input of $f$ is a tuple of 2 random vectors (interpreted as numbers $\in \mathbb C$) and its output is a single 2x1 matrix where both values $\in \mathbb R$, then the desired function satisfies the condition. => $\mathbb C$ is closed under multipliation and addition. Moreover, if we consider the case where we're multiplying a vector by a non-zero constant i.e. scalar multiplication, we can see that this property is still closed under $\mathbb C$. We can proove this by choosing an arbitrary non-zero number $x \in \mathbb R$ and an arbitrary non-zero constant $c_1 \in \mathbb R$. Now, we know from the properties of R that $c_1x \in \mathbb R$. Now, if we were to choose a pair of arbitrary numbers $x$ and $y$, by the same logic $c_1x \in \mathbb R$ and $c_1y \in \mathbb R$. Therefore, $(c_1x + c_1y) \in \mathbb R^2$. And since we know that $\mathbb C$ is defined as $\mathbb R^2$, then $(c_1x + c_1y) \in \mathbb C$. Lastly, the zero vector in $\mathbb C$ is $(0 + 0i)$.

2. Two different subspaces of $\mathbb C$ are as follows: 
$$\\ \begin{cases} y = 0, & i.e.\ \mathbb R \\  x = 0, & i.e.\ \Re (z)= \Re(x+iy)= \Re(iy) = 0 \end{cases}$$
(Another possible subsets of $\mathbb C$ are $\mathbb Q$ and $\mathbb Z$) Why this is true?
Well, for the first case, we can choose the following:
Let  $𝑥\in \mathbb R$. Since  $𝑥 = (x + 0i) \in \mathbb C$, then $x \in \mathbb C$. Since $x$ was arbitrary it follows that $\mathbb R \subset \mathbb C$. Analogously, we can use the same method to prove that the second subspace is also a subspace of $\mathbb C$ since we can just start by choosing an arbitrary $y \in \mathbb R$.
They satisfy the definition of a substace since: 1) they are non-empty (for example, $1$ and $i$ are in the 1st and 2nd set respectively and none of those numbers is 0); 2) they are both closed under scalar multipliation; 3) they are both closed under addition. 

3. Let's choose two arbitrary vectors in $\mathbb C$: $$ \begin{bmatrix}
x_1 \\ y_1 \end{bmatrix}\ and\ \begin{bmatrix}
x_2 \\ y_2 \end{bmatrix}$$ We know that: $x_1, x_2, y_1, y_2 \in \mathbb R$.
Let's calculate their product: $$(x_1 + y_1i)(x_2 + y_2i) = \\ = x_1x_2 + x_1(y_2i) + (y_1i)x_2 + (y_1i)(y_2i) = \\ = x_1x_2 + (x_1y_2 + x_2y_1)i + y_1y_2(i^2) = \\ = (x_1x_2 - y_1y_2) + (x_1y_2 + x_2y_1)i$$
Now, since we know that $\mathbb R$ is closed under multipliation and addition, then because $x_1, x_2, y_1, y_2 \in \mathbb R$, we also know that $(x_1x_2 - y_1y_2), (x_1y_2 + x_2y_1) \in \mathbb R$. Since we multiplied a random tuple of real numbers with another one and we got a new tuple of real numbers, then we know that $\mathbb C$ is closed under multipliation!

# Problem 4 (20 points)

Consider the following linear system of equations:

$$ \begin{align*}
3x_2 - 6x_3 + 6x_4 + 4x_5 &= -5 \\
3x_1 - 7x_2 + 8x_3 - 5x_4 + 8x_5 &= 9 \\
3x_1 - 9x_2 + 12x_3 - 9x_4 + 6x_5 &= 15
\end{align*} $$

1. Form the augmented matrix for this linear system. Complete the following statement: "The solution to this system is the intersection of _ hyperplanes embedded in _-dimensional space."

2. Write out (in English) the sequence of row operations needed to transform the augmented matrix into row echelon form. Each one should say something like "scale row x by y" or "replace row z with ...". You may use Gaussian elimination in Python to check your work; please leave all commands and outputs below if you do so.

3. Write down the elimination matrices corresponding to each of the row operations above. Compute their product $X$, ordered in the same way as the row operations (you may use Python).

4. Compute the products $XA$ and $X \mathbf b$. Explain how these results are related to the REF of the augmented matrix you computed in part 2.


ENTER YOUR SOLUTIONS HERE 

1. The augmented matrix for the following system of equations is: 
$$ \begin{bmatrix}
0 & 3 & -6 & 6 & 4 & | & -5 \\ 
3 & -7 & 8 & -5 & 8 & | & 9 \\
3 & -9 & 12 & -9 & 6 & | & 15
\end{bmatrix} $$
The solution to this system is the intersection of 3 hyperplanes embedded in 5-dimensional space.

2. Since our matrix already has a zero in A[0][0], we can leave the first row as is. Now, to get a 0 in A[1][0], we can replace row 2 with (row 3 - row 2). This operation will give us: 
$$\begin{bmatrix}
3 & -9 & 12 & -9 & 6 & | & 15 \\ 
\end{bmatrix} - \begin{bmatrix}
3 & -7 & 8 & -5 & 8 & | & 9
\end{bmatrix} \\ = \begin{bmatrix}
0 & -2 & 4 & -4 & -2 & | & 6
\end{bmatrix} $$ Now we can scale row 2 by $\frac{1}{2}$ and this will give us the row: $$\begin{bmatrix}
0 & -1 & 2 & -2 & -1 & | & 3
\end{bmatrix}$$ Now we can scale row 3 by $\frac{1}{3}$ and this will give us the row: $$\begin{bmatrix}1 & -3 & 4 & -3 & 2 & | & 5\end{bmatrix}$$ Now the matrix has become:
$$ \begin{bmatrix}
0 & 3 & -6 & 6 & 4 & | & -5 \\ 
0 & -1 & 2 & -2 & -1 & | & 3 \\
1 & -3 & 4 & -3 & 2 & | & 5
\end{bmatrix} $$
To get the REF we need to swap row 3 and row 1, which will result in:
$$ \begin{bmatrix}
1 & -3 & 4 & -3 & 2 & | & 5 \\
0 & -1 & 2 & -2 & -1 & | & 3 \\ 
0 & 3 & -6 & 6 & 4 & | & -5 \\
\end{bmatrix} $$ Now we only need to get a 0 at A[2][0], which we can get by replacing row 3 with (3 * row 2 + row 3). Calculating (3 * row 2 + row 3 ) gives us: 
$$3 * \begin{bmatrix}
0 & -1 & 2 & -2 & -1 & | & 3 \\
\end{bmatrix} + \begin{bmatrix}
0 & 3 & -6 & 6 & 4 & | & -5 \\
\end{bmatrix} \\ = \begin{bmatrix}
0 & -3 & 6 & -6 & -3 & | & 9 \\
\end{bmatrix} + \begin{bmatrix}
0 & 3 & -6 & 6 & 4 & | & -5 \\ 
\end{bmatrix} = \\  \begin{bmatrix}
0 & 0 & 0 & 0 & 1 & | & 4 \\ 
\end{bmatrix} $$ Now finally we get: 
$$ \begin{bmatrix}
1 & -3 & 4 & -3 & 2 & | & 5 \\
0 & -1 & 2 & -2 & -1 & | & 3 \\ 
0 & 0 & 0 & 0 & 1 & | & 4 \\
\end{bmatrix} $$ 


3. The operations we did in 4.2 are as follows:
    1. Row 2 $\rightarrow$ (Row 3 - Row 2)
    2. Row 2 $\rightarrow$ (Row 2) $* \frac12$
    3. Row 3 $\rightarrow$ (Row 3) $* \frac13$
    4. Swap(Row 1, Row 3) i.e. (Row 3, Row 1) $\rightarrow$ (Row 1, Row 3)
    5. Row 3 $\rightarrow$ (3 * Row 2 + Row 3)

    It follows that we'll need (at least) 5 elimination matrices in order to get to the result that we want. However, we can see that the first and last operations should be broken into 2 operations, as follows: 
    
    1. a) Row 2 $\rightarrow$ (- Row 2)
    1. b) Row 2 $\rightarrow$ (Row 2 + Row 3)
    5. a) Row 2 $\rightarrow$ (3 * Row 2)
    5. b) Row 3 $\rightarrow$ (Row 3 + Row 2)

    Note: Now, since we are multiplying Row 2 by 3 and we want to perserve it, we have to do one additional final operation which negates 5a): 
    
    6. Row 2 $\rightarrow$ ($\frac{1}{3}$ * Row 2)

    Now, the elimination matrices are as follows:

    1. a) $$ X_1 = 
    \begin{bmatrix}
    1 & 0 & 0 \\ 
    0 & -1 & 0 \\
    0 & 0 & 1 \end{bmatrix} $$
    1. b) $$ X_2 = 
    \begin{bmatrix}
    1 & 0 & 0 \\ 
    0 & 1 & 1 \\
    0 & 0 & 1 \end{bmatrix} $$
    2. $$ X_3 = 
    \begin{bmatrix}
    1 & 0 & 0 \\ 
    0 & \frac{1}{2} & 0 \\
    0 & 0 & 1 \end{bmatrix} $$
    3. $$ X_4 = 
    \begin{bmatrix}
    1 & 0 & 0 \\ 
    0 & 1 & 0 \\
    0 & 0 & \frac{1}{3} \end{bmatrix} $$
    4. $$ X_5 = 
    \begin{bmatrix}
    0 & 0 & 1 \\ 
    0 & 1 & 0 \\
    1 & 0 & 0 \end{bmatrix} $$
    5. a) $$ X_6 = 
    \begin{bmatrix}
    1 & 0 & 0 \\ 
    0 & 3 & 0 \\
    0 & 0 & 1 \end{bmatrix} $$
    5. b) $$ X_7 = 
    \begin{bmatrix}
    1 & 0 & 0 \\ 
    0 & 3 & 0 \\
    0 & 1 & 1 \end{bmatrix} $$
    6. $$ X_8 = 
    \begin{bmatrix}
    1 & 0 & 0 \\ 
    0 & \frac{1}{3} & 0 \\
    0 & 0 & 1 \end{bmatrix} $$

    If we want to calculate the product of the above elimination matrices: $X$ = ${\displaystyle \prod_{i=8}^{1} X_{i}}$ we'll get: $$ X = 
    \begin{bmatrix}
    0 & 0 & \frac{1}{3} \\ 
    0 & -\frac{1}{2} & \frac{1}{2} \\
    1 & -\frac{3}{2} & \frac{1}{2} \end{bmatrix} $$

4. The products are computed with numpy and the code is below. Moreover, we can see that the products $XA$ and $Xb$ are actually the first (m-1) columns of the augmented matrix and the last -i.e. (m)-th- matrix column respectively.


In [26]:
# ENTER ANY CODE HERE

# Calculating the X matrix for 4c):

X_1 = np.array([[1, 0,  0],
                [0, -1, 0],
                [0, 0,  1]])

X_2 = np.array([[1, 0, 0],
                [0, 1, 1],
                [0, 0, 1]])

X_3 = np.array([[1, 0,   0],
                [0, 0.5, 0],
                [0, 0,   1]])

X_4 = np.array([[1, 0,   0],
                [0, 1,   0],
                [0, 0, 1/3]])

X_5 = np.array([[0, 0, 1],
                [0, 1, 0],
                [1, 0, 0]])

X_6 = np.array([[1, 0, 0],
                [0, 3, 0],
                [0, 0, 1]])

X_7 = np.array([[1, 0, 0],
                [0, 1, 0],
                [0, 1, 1]])

X_8 = np.array([[1, 0,   0],
                [0, 1/3, 0],
                [0, 0,   1]])

result = X_8 @ (X_7 @ (X_6 @ (X_5 @ (X_4 @ (X_3 @ (X_2 @ X_1))))))

print(result)

[[ 0.          0.          0.33333333]
 [ 0.         -0.5         0.5       ]
 [ 1.         -1.5         1.5       ]]


In [27]:
# Calculating XA and Xb for 4d):
X = np.array([[0, 0,     1/3],
              [0, -1/2,  1/2],
              [1, -3/2,  3/2]])

A = np.array([[0,  3, -6,  6, 4],
              [3, -7,  8, -5, 8],
              [3, -9, 12, -9, 6]])

b = np.array([-5, 9, 15])

print("The XA multiplication is:")
print(X @ A)

print("The Xb multiplication is:")
print(X @ b)

The XA multiplication is:
[[ 1. -3.  4. -3.  2.]
 [ 0. -1.  2. -2. -1.]
 [ 0.  0.  0.  0.  1.]]
The Xb multiplication is:
[5. 3. 4.]


# Problem 5 (20 points)

We will continue to study the linear system in the above problem. Regardless of your work there, you should run Gauss-Jordan elimination on this system in Python before starting this problem.

1. Show the matrix $R$, the RREF of $A$. How many pivot variables does it have? How many free variables does it have? What is the rank of $A$ and of $R$? Which of these values, if any, depend on the vector $\mathbf b$?

2. Starting from $R$, solve for $A \mathbf x = \mathbf 0$ and give the null space of $A$. Express it as the span of several vectors, each of which has a value of 1 for a free variable and 0 for all other free variables.

3. Now find a particular solution to the original system $A \mathbf x = \mathbf b$ in which all free variables are set to 0. Write down the complete solution by combining it with the null space expression from the previous part.

4. Consider a different system with the same coefficient matrix: $A \mathbf x = \mathbf c$. Explain whether it is possible for such a system to have a unique solution or no solution given what we know about $A \mathbf x = \mathbf b$.

ENTER YOUR SOLUTIONS HERE 

1. The matrix $R$ is as follows:
$$ \begin{bmatrix}
1 & 0 & -2 & 3 & 0 \\
0 & 1 & -2 & 2 & 0 \\ 
0 & 0 & 0 & 0 & 1  \\
\end{bmatrix} $$ 
We got this result from the code block after 5.4. 
From the result for $R$ we can see that the free variables are $x_3$ and $x_4$. Moreover, the pivot variables are $x_1$, $x_2$, and $x_5$. The rank of $A$ is 3, because $R$ is the RREF matrix and we just need to count its non-zero rows. The rank of $R$ is the same as the rank of $A$ since the matrix $R$ is just $A$ after a couple of row transformations. No values depend on $b$.


2. We have the vector: $$\mathbf x = \begin{bmatrix}
x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5 \\ \end{bmatrix}$$ Now, if we want to represent the given equation:
$$ \begin{bmatrix}
1 & 0 & -2 & 3 & 0 \\
0 & 1 & -2 & 2 & 0 \\ 
0 & 0 & 0 & 0 & 1  \\
\end{bmatrix} 
\begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5 \\ \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \\ \end{bmatrix}$$
This can be rewritten in linear equations form the follwing way: 
$$\\ \begin{cases} 
        x_1 - 2x_3 + 3x_4 = 0 
    \\  x_2 - 2x_3 + 2x_4 = 0
    \\  x_5 = 0 
       \end{cases}$$
From here, we can quickly get:
$$\\ \begin{cases} 
        x_1 = 2x_3 - 3x_4 
    \\  x_2 = 2x_3 - 2x_4
    \\  x_5 = 0 
       \end{cases}$$
From this it follows that $\mathbf x$ is:
$$\begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5 \\ \end{bmatrix} = \begin{bmatrix} 2x_3 - 3x_4\\ 2x_3 - 2x_4 \\ x_3 \\ x_4 \\ 0 \\ \end{bmatrix} = x_3\begin{bmatrix} 2 \\ 2 \\ 1 \\ 0 \\ 0 \\ \end{bmatrix} + x_4\begin{bmatrix} -3 \\ -2 \\ 0 \\ 1 \\ 0 \end{bmatrix}$$

=> The null space is: $$Span\Bigg\{\begin{bmatrix} 2 \\ 2 \\ 1 \\ 0 \\ 0 \\ \end{bmatrix}, \begin{bmatrix} -3 \\ -2 \\ 0 \\ 1 \\ 0 \end{bmatrix}\Bigg\}$$


3. To find a particular solution, we need to set all free variables to 0. In our case this means: $x_3 = 0, x_4 = 0$. Plugging those values, we'll get: 
$$\\ \begin{cases} 
        x_1 - 2(0) + 3(0) = -24
    \\  x_2 - 2(0) + 2(0) = -7
    \\  x_5 = 4
       \end{cases} => 
       \begin{cases} 
        x_1 = -24 
    \\  x_2 = -7
    \\  x_5 = 4
       \end{cases}$$
=> Our particular solution is: 
$$\mathbf x_p = \begin{bmatrix} -24 \\ -7 \\ 0 \\ 0 \\ 4 \end{bmatrix}$$
Getting the complete solution by combining it with the null space expression from the previous part:
$$\mathbf x_{complete} = \begin{bmatrix} -24 \\ -7 \\ 0 \\ 0 \\ 4 \end{bmatrix} + c_1\begin{bmatrix} 2 \\ 2 \\ 1 \\ 0 \\ 0 \\ \end{bmatrix} + c_2\begin{bmatrix} -3 \\ -2 \\ 0 \\ 1 \\ 0 \end{bmatrix}$$ for some $c_1, c_2 \in \R$.

4. Since we have 3 rows of the matrix $A$ and we have 5 variables in total, of which 2 are free variables, for an arbitrary vector $c$ we can get a solution for the pivot variables ($x_1, x_2,\ and\ x_5$), but the free variables can take any arbitrary values. We can see this also by acknowledging that there is no possiblity for 0 solutions since we don't have a row in $A$ filled only with zeroes. Moreover, if there was a sole solution, $A$'s rank should've been at least 5 as opposed to it being 3. => For an arbitrary $c$, there's an infinite number of solutions! 

In [28]:
# ENTER ANY CODE HERE

# Gauss-Jordan Elimination from class notes
def GJE(A):
  A = A.astype(float)
  pr = 0    # row with current pivot
  pc = 0    # col with current pivot
  
  while pr < A.shape[0] and pc < A.shape[1]:  # run until last row or last column
    nonzeros = np.nonzero(A[pr:,pc])[0]       # find nonzero entries in column
    if nonzeros.size == 0:                    # no nonzero entries, move to next column
      pc += 1

    else:
      row = nonzeros[0] + pr
      A[[pr, row]] = A[[row, pr]]               # swap rows with the found pivot
      A[pr] /= A[pr,pc]                         # rescale pivot entry to 1
      A[pr+1:] -= np.outer(A[pr+1:,pc], A[pr])  # row-reduce all rows below pivot
      A[:pr] -= np.outer(A[:pr,pc], A[pr])      # row-reduce all rows above pivot
      pr += 1                                   # move to next pivot position
      pc += 1
  
  return A

In [29]:
augmentedA = np.array([[0,  3, -6,  6, 4, -5],
                       [3, -7,  8, -5, 8,  9],
                       [3, -9, 12, -9, 6, 15]])
print(augmentedA) # Printing the original A matrix
print()

print(GJE(augmentedA)) # Printing the A matrix after Gauss-Jordan Elimination 

[[ 0  3 -6  6  4 -5]
 [ 3 -7  8 -5  8  9]
 [ 3 -9 12 -9  6 15]]

[[  1.   0.  -2.   3.   0. -24.]
 [  0.   1.  -2.   2.   0.  -7.]
 [  0.   0.   0.   0.   1.   4.]]


# Problem 6 (15 points)

In this problem we will explore some general and practical implications of matrix rank.

1. Pick two different values $m$ and $n$, each 3 or larger. Create two random matrices using [numpy.random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html): $A$ with size $m \times n$ and $B$ with size $n \times m$. Then use [numpy.linalg.matrix_rank](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html) to compute the rank of each. In general, what is the rank of a random $m \times n$ matrix?

2. Compute two matrix products: $AB$ and $BA$. What are their ranks, and what can you say about the upper bound of the rank of the product of two matrices? Considering another generic matrix $C$ with rank $r$, what can you say about the ranks of $C^\top C$ and $C C^\top$ from these observations?

3. Take the larger of the two matrix products that you computed above (the one with more rows and more columns). Modify it in three different ways by adding to it a matrix $\lambda I$, with $\lambda = 1$, $\lambda = 10^{-4}$, and $\lambda = 10^{-8}$. What are the ranks of each of the matrix sums? Given a generic matrix, how would you propose to make it full rank by minimally changing the matrix values?

ENTER WRITTEN RESPONSES HERE

1. In general, the rank of $m$ x $n$ matrix is $min(m, n)$. We know that if the matrix is full column/row, its rank can be at most $min(m, n)$. When we get random values, it's very uncommon that a row/column can be represented as a constant multiplied by another row/column and, thus it's expected that the rank will be the largest possible number, i.e.$min(m, n)$.

2. Their ranks are both $min(m, n)$. The upper bound for a product of 2 matrices is $min(m, n)$. According to those observations, the ranks of both $C^\top C$ and $C C^\top$ are $r$.

3. The ranks of all 3 matrices of the type $BA + I\lambda$ are 6. This means that $BA + I\lambda$ produces a full rank matrix for any value of $\lambda \ne 0$. This means that for a generic matrix, we can make it full rank by adding a small constant to its diagonal entries.

In [30]:
# CODE FOR 6.1
from numpy.linalg import matrix_rank

rng = np.random.default_rng()

# Let's choose N = 5, M = 6
M = 5
N = 6

matrixA = rng.random((M, N))
matrixB = rng.random((N, M))

# Printing the randomized matricies
print(matrixA)
print()
print(matrixB)
print()

print(f"Rank of matrix A: {matrix_rank(matrixA)}")
print(f"Rank of matrix B: {matrix_rank(matrixB)}")

[[0.15029556 0.0264439  0.45533826 0.19180667 0.88522504 0.15049113]
 [0.59936336 0.34761389 0.98832313 0.68073534 0.25680119 0.78512206]
 [0.28035972 0.56804419 0.83369285 0.70876044 0.86131243 0.37916006]
 [0.21692437 0.13959791 0.23467067 0.05044151 0.25708714 0.8737352 ]
 [0.81026999 0.93702839 0.37012872 0.72528843 0.17885707 0.19507391]]

[[0.89664904 0.51913123 0.61721367 0.08638015 0.70700368]
 [0.29960846 0.40951167 0.9687009  0.33942234 0.27383819]
 [0.47127118 0.43188813 0.51687578 0.67789786 0.33515432]
 [0.44340428 0.9332316  0.22448849 0.8297477  0.56495267]
 [0.30347576 0.3646244  0.50895987 0.01020891 0.31073149]
 [0.44318171 0.76246384 0.97483918 0.69492588 0.3249525 ]]

Rank of matrix A: 5
Rank of matrix B: 5


In [31]:
# CODE FOR 6.2

productAB = matrixA @ matrixB
productBA = matrixB @ matrixA

# Printing the product of the randomized matricies
print(productAB)
print()
print(productBA)
print()

print(f"Rank of matrix AB: {matrix_rank(productAB)}")
print(f"Rank of matrix BA: {matrix_rank(productBA)}")

[[0.77766014 0.90202613 0.99404108 0.60339954 0.6984409 ]
 [1.83506049 2.2078921  2.26639592 1.95280502 1.56968967]
 [1.5581622  2.00281526 2.12132451 1.64255654 1.42444532]
 [0.83453243 1.07813602 1.38433478 0.87686286 0.66254903]
 [1.64402841 1.85502925 2.04313619 1.37814333 1.48222818]]

[[1.21055428 1.22931377 1.71786791 1.47996961 1.60732334 0.98993322]
 [0.85757266 1.00451648 1.52975991 1.23854549 1.34097713 1.08388168]
 [0.89321708 0.86488308 1.35548145 1.02801331 1.2075055  1.26366876]
 [1.32668074 1.10885672 1.71521042 1.33104755 1.13988552 1.71973349]
 [0.66083637 0.71647465 1.04027344 0.89303692 0.85885489 0.59445782]
 [1.21095239 1.23201413 2.05142767 1.56570614 1.66453483 1.70551313]]

Rank of matrix AB: 5
Rank of matrix BA: 5


In [32]:
# CODE FOR 6.3

# The larger of the 2 matricies is BA, because it is 6x6 versus AB which is 5x5

lambda_values = [
    10**(0),
    10**(-4),
    10**(-8)
]

identity_matrix = [[1 for i in range(N)] for j in range(N)]
identity_matrix = np.array(identity_matrix)

matricies = [(productBA + (identity_matrix * lambda_val)) for lambda_val in lambda_values]
matricies_ranks = [matrix_rank(matrix) for matrix in matricies]

[print(f"Rank of matrix with lambda value = {lambda_values[i]} is {matricies_ranks[i]}") for i in range(len(matricies))]

Rank of matrix with lambda value = 1 is 6
Rank of matrix with lambda value = 0.0001 is 6
Rank of matrix with lambda value = 1e-08 is 6


[None, None, None]